FROM maven:3.8.5-openjdk-17-slim AS build

COPY . .

RUN mvn clean package -DskipTests


FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build target/ByteMeBistro-1.0.0.jar app.jar

EXPOSE 1337

ENTRYPOINT ["java", "-jar", "app.jar"]

